spring:
  application:
    name: k-cache-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/data/k-cache-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: admin
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /db/h2-console

server:
  port: 5500
  servlet:
    context-path: /kCacheService/api

cache:
  max-size: 5

logging:
  level:
    org.example.kcacheservice: debug
    org.springframework.web: info
    org.hibernate.SQL: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

